version: "3.7"

services:
  sonnet:
    build:
      context: app
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: sonnet
    env_file:
      - .env
    volumes:
      - ./app:/app
    environment:
      TESTING_URL: ${TESTING_URL}
